[package]
name = "noiseexplorer_inpsk1_wasm"
version = "1.0.4"
authors = ["Symbolic Software <georgio@symbolic.software>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake2-rfc = "0.2.18"
constant_time_eq = "0.1.5"
chacha20-poly1305-aead = {version = "0.1.2", git = "https://github.com/symbolicsoft/chacha20-poly1305-aead"}
getrandom = "0.1.3"
hex = "0.4.3"
rust-crypto-wasm = "0.3.1"
zeroize = "1.3.0"
wasm-bindgen = "0.2.46"

[dev-dependencies]
wasm-bindgen-test = "0.2"

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
debug-js-glue = true
demangle-name-section = true
dwarf-debug-info = false

[package.metadata.wasm-pack.profile.profiling.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false